version: '2.2'

services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:4.0.1"
    container_name: "zookeeper"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  kafka:
    image: "confluentinc/cp-kafka:4.0.1"
    container_name: "kafka"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:32181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    restart: always
    depends_on:
      zookeeper:
        condition: service_started
